/* =============================================================================
   Strategy Cadet, Fleetwood Limited (ASX: FWD)
   Report config for the Strategy Cadet Report Viewer chassis.

   Build date: 2026-05-25
   Brand discovery source: brand-discovery-skill/output/
     fleetwood-modular-construction-and-recreational-vehicles-discovery_2026-05-25.md
   ============================================================================= */

const REPORT = {
  client:    'Fleetwood Limited',
  agency:    'Anthony Charles',
  subtitle:  'Brand and Media Analysis, Modular Construction and Recreational Vehicles',
  version:   'Build 01.1',
  date:      '25 May 2026',
  copyright: '© 2026 York Studios Pty Ltd',
};

const slideData = [
  { num:  1, src: 'slides/00a-overview-cover.html?chrome=off&v=2654', title: 'StratCadet Overview Cover' },
  { num:  2, src: 'slides/00b-overview-chapters.html?chrome=off&v=2654', title: 'What it Delivers - 8 Chapters' },
  { num:  3, src: 'slides/00c-overview-engine.html?chrome=off&v=2654', title: 'How it Works - The Engine' },
  { num:  4, src: 'slides/00d-overview-moats.html?chrome=off&v=2654', title: 'Two Moats and Four Confidence Tags' },
  { num:  5, src: 'slides/01-cover.html?chrome=off&v=2654', title: 'Cover' },
  { num:  6, src: 'slides/03-divider-market.html?chrome=off&v=2654', title: 'Divider Market' },
  { num:  7, src: 'slides/04-quick-facts.html?chrome=off&v=2654', title: 'Quick Facts' },
  { num:  8, src: 'slides/05-industry-drivers.html?chrome=off&v=2654', title: 'Industry Drivers' },
  { num:  9, src: 'slides/06-macro-influences.html?chrome=off&v=2654', title: 'Macro Influences' },
  { num: 10, src: 'slides/07-market-size.html?chrome=off&v=2654', title: 'Market Size' },
  { num: 11, src: 'slides/08-divider-brand.html?chrome=off&v=2654', title: 'Divider Brand' },
  { num: 12, src: 'slides/09-brand-founders-spirit.html?chrome=off&v=2654', title: 'Brand Founders Spirit' },
  { num: 13, src: 'slides/10-brand-expertise-innovation.html?chrome=off&v=2654', title: 'Brand Expertise Innovation' },
  { num: 14, src: 'slides/11-brand-sustainability-legacy.html?chrome=off&v=2654', title: 'Brand Sustainability Legacy' },
  { num: 15, src: 'slides/12-brand-personality.html?chrome=off&v=2654', title: 'Brand Personality' },
  { num: 16, src: 'slides/13-brand-purpose-mission.html?chrome=off&v=2654', title: 'Brand Purpose Mission' },
  { num: 17, src: 'slides/14-brand-customer-experience.html?chrome=off&v=2654', title: 'Brand Customer Experience' },
  { num: 18, src: 'slides/15-brand-personality-radar.html?chrome=off&v=2654', title: 'Brand Personality Radar' },
  { num: 19, src: 'slides/16-brand-messaging-themes.html?chrome=off&v=2654', title: 'Brand Messaging Themes' },
  { num: 20, src: 'slides/17-divider-audiences.html?chrome=off&v=2654', title: 'Divider Audiences' },
  { num: 21, src: 'slides/18-audience-1-profile.html?chrome=off&v=2654', title: 'Audience 1 Profile' },
  { num: 22, src: 'slides/19-audience-2-profile.html?chrome=off&v=2654', title: 'Audience 2 Profile' },
  { num: 23, src: 'slides/20-audience-3-profile.html?chrome=off&v=2654', title: 'Audience 3 Profile' },
  { num: 24, src: 'slides/21-audience-1-cultural-signals.html?chrome=off&v=2654', title: 'Audience 1 Cultural Signals' },
  { num: 25, src: 'slides/22-audience-2-cultural-signals.html?chrome=off&v=2654', title: 'Audience 2 Cultural Signals' },
  { num: 26, src: 'slides/23-audience-3-cultural-signals.html?chrome=off&v=2654', title: 'Audience 3 Cultural Signals' },
  { num: 27, src: 'slides/24-audience-summary.html?chrome=off&v=2654', title: 'Audience Summary' },
  { num: 28, src: 'slides/25-divider-innovation.html?chrome=off&v=2654', title: 'Divider Innovation' },
  { num: 29, src: 'slides/26-emerging-trends-modular.html?chrome=off&v=2654', title: 'Emerging Trends Modular' },
  { num: 30, src: 'slides/27-emerging-trends-rv.html?chrome=off&v=2654', title: 'Emerging Trends RV' },
  { num: 31, src: 'slides/28-innovation-builder-aud1.html?chrome=off&v=2654', title: 'Innovation Builder AUD1' },
  { num: 32, src: 'slides/29-innovation-builder-aud2.html?chrome=off&v=2654', title: 'Innovation Builder AUD2' },
  { num: 33, src: 'slides/30-innovation-builder-aud3.html?chrome=off&v=2654', title: 'Innovation Builder AUD3' },
  { num: 34, src: 'slides/31-divider-competitive.html?chrome=off&v=2654', title: 'Divider Competitive' },
  { num: 35, src: 'slides/32-competitors-modular.html?chrome=off&v=2654', title: 'Competitors Modular' },
  { num: 36, src: 'slides/33-competitors-rv.html?chrome=off&v=2654', title: 'Competitors RV' },
  { num: 37, src: 'slides/34-competitor-forensics-5b.html?chrome=off&v=2654', title: 'Competitor Forensics 5b' },
  { num: 38, src: 'slides/35-brand-corporate-forensics-5c.html?chrome=off&v=2654', title: 'Brand Corporate Forensics 5c' },
  { num: 39, src: 'slides/36-esov-positioning.html?chrome=off&v=2654', title: 'ESOV Positioning' },
  { num: 40, src: 'slides/37-divider-brand-strategy.html?chrome=off&v=2654', title: 'Divider Brand Strategy' },
  { num: 41, src: 'slides/38-strategy-pillars.html?chrome=off&v=2654', title: 'Strategy Pillars' },
  { num: 42, src: 'slides/39-strategic-goal.html?chrome=off&v=2654', title: 'Strategic Goal' },
  { num: 43, src: 'slides/40-kpi-tree.html?chrome=off&v=2654', title: 'KPI Tree' },
  { num: 44, src: 'slides/41-initiatives.html?chrome=off&v=2654', title: 'Initiatives' },
  { num: 45, src: 'slides/42-roadmap-cadence.html?chrome=off&v=2654', title: 'Roadmap Cadence' },
  { num: 46, src: 'slides/43-kill-switches.html?chrome=off&v=2654', title: 'Kill Switches' },
  { num: 47, src: 'slides/44-brand-opportunities.html?chrome=off&v=2654', title: 'Brand Opportunities' },
  { num: 48, src: 'slides/45-five-actions.html?chrome=off&v=2654', title: 'Five Actions' },
  { num: 49, src: 'slides/46-divider-marketing.html?chrome=off&v=2654', title: 'Divider Marketing' },
  { num: 50, src: 'slides/47-aud1-channel-messaging.html?chrome=off&v=2654', title: 'AUD1 Channel Messaging' },
  { num: 51, src: 'slides/48-aud1-budget-measurement.html?chrome=off&v=2654', title: 'AUD1 Budget Measurement' },
  { num: 52, src: 'slides/49-aud1-tactics.html?chrome=off&v=2654', title: 'AUD1 Tactics' },
  { num: 53, src: 'slides/50-aud2-channel-messaging.html?chrome=off&v=2654', title: 'AUD2 Channel Messaging' },
  { num: 54, src: 'slides/51-aud2-budget-measurement.html?chrome=off&v=2654', title: 'AUD2 Budget Measurement' },
  { num: 55, src: 'slides/52-aud2-tactics.html?chrome=off&v=2654', title: 'AUD2 Tactics' },
  { num: 56, src: 'slides/53-aud3-channel-messaging.html?chrome=off&v=2654', title: 'AUD3 Channel Messaging' },
  { num: 57, src: 'slides/54-aud3-budget-measurement.html?chrome=off&v=2654', title: 'AUD3 Budget Measurement' },
  { num: 58, src: 'slides/55-aud3-tactics.html?chrome=off&v=2654', title: 'AUD3 Tactics' },
  { num: 59, src: 'slides/56-divider-geo.html?chrome=off&v=2654', title: 'Divider GEO' },
  { num: 60, src: 'slides/57-geo-scorecard.html?chrome=off&v=2654', title: 'GEO Scorecard' },
  { num: 61, src: 'slides/58-news-pr.html?chrome=off&v=2654', title: 'News PR' },
  { num: 62, src: 'slides/59-reviews-trust.html?chrome=off&v=2654', title: 'Reviews Trust' },
  { num: 63, src: 'slides/60-share-of-search.html?chrome=off&v=2654', title: 'Share Of Search' },
  { num: 64, src: 'slides/61-divider-appendix.html?chrome=off&v=2654', title: 'Divider Appendix' },
  { num: 65, src: 'slides/62-ceps-master.html?chrome=off&v=2654', title: 'CEPS Master' },
  { num: 66, src: 'slides/63-data-gaps.html?chrome=off&v=2654', title: 'Data Gaps' },
  { num: 67, src: 'slides/64-source-coverage.html?chrome=off&v=2654', title: 'Source Coverage' },
  { num: 68, src: 'slides/65-divider-extended.html?chrome=off&v=2654', title: 'Divider Extended' },
  { num: 69, src: 'slides/66-market-size-esov.html?chrome=off&v=2654', title: 'Market Size ESOV' },
  { num: 70, src: 'slides/67-industry-drivers.html?chrome=off&v=2654', title: 'Industry Drivers' },
  { num: 71, src: 'slides/68-macro-influences.html?chrome=off&v=2654', title: 'Macro Influences' },
  { num: 72, src: 'slides/69-customer-problem.html?chrome=off&v=2654', title: 'Customer Problem' },
  { num: 73, src: 'slides/70-value-proposition.html?chrome=off&v=2654', title: 'Value Proposition' },
  { num: 74, src: 'slides/71-divider-methodology.html?chrome=off&v=2654', title: 'Divider Methodology' },
  { num: 75, src: 'slides/72-methodology.html?chrome=off&v=2654', title: 'Methodology' },
  { num: 76, src: 'slides/73-citations-1.html?chrome=off&v=2654', title: 'Citations 1' },
  { num: 77, src: 'slides/74-citations-2.html?chrome=off&v=2654', title: 'Citations 2' },
  { num: 78, src: 'slides/75-citations-3.html?chrome=off&v=2654', title: 'Citations 3' },
  { num: 79, src: 'slides/76-brand-dna.html?chrome=off&v=2654', title: 'Brand DNA' },
  { num: 80, src: 'slides/77-strategy-pillars.html?chrome=off&v=2654', title: 'Strategy Pillars' },
  { num: 81, src: 'slides/78-emerging-trends.html?chrome=off&v=2654', title: 'Emerging Trends' },
  { num: 82, src: 'slides/79-positioning-matrix.html?chrome=off&v=2654', title: 'Positioning Matrix' },
  { num: 83, src: 'slides/80-data-sources.html?chrome=off&v=2654', title: 'Data Sources' },
  { num: 84, src: 'slides/81-back-cover.html?chrome=off&v=2654', title: 'Back Cover' },
]
;

// =============================================================================
// indexData — TOC by part (used by chassis sidebar)
// =============================================================================
const indexData = [
  { title: '<strong>STRATEGY CADET OVERVIEW</strong>', dividerSlide: 1, subs: [
    { label: 'What it Delivers (8 chapters)', slide: 2 },
    { label: 'How it Works (the engine)', slide: 3 },
    { label: 'Two Moats + 4 Confidence Tags', slide: 4 },
  ]},
  { title: '01 - The Market', dividerSlide: 6, subs: [
    { label: 'Quick Facts', slide: 7 },
    { label: 'Industry Drivers', slide: 8 },
    { label: 'Macro Influences', slide: 9 },
    { label: 'Market Size', slide: 10 },
  ]},
  { title: '02 - Brand', dividerSlide: 11, subs: [
    { label: 'Brand Founders Spirit', slide: 12 },
    { label: 'Brand Expertise Innovation', slide: 13 },
    { label: 'Brand Sustainability Legacy', slide: 14 },
    { label: 'Brand Personality', slide: 15 },
    { label: 'Brand Purpose Mission', slide: 16 },
    { label: 'Brand Customer Experience', slide: 17 },
    { label: 'Brand Personality Radar', slide: 18 },
    { label: 'Brand Messaging Themes', slide: 19 },
  ]},
  { title: '03 - Audiences', dividerSlide: 20, subs: [
    { label: 'Audience 1 Profile', slide: 21 },
    { label: 'Audience 2 Profile', slide: 22 },
    { label: 'Audience 3 Profile', slide: 23 },
    { label: 'Audience 1 Cultural Signals', slide: 24 },
    { label: 'Audience 2 Cultural Signals', slide: 25 },
    { label: 'Audience 3 Cultural Signals', slide: 26 },
    { label: 'Audience Summary', slide: 27 },
  ]},
  { title: '04 - Innovation', dividerSlide: 28, subs: [
    { label: 'Emerging Trends Modular', slide: 29 },
    { label: 'Emerging Trends RV', slide: 30 },
    { label: 'Innovation Builder AUD1', slide: 31 },
    { label: 'Innovation Builder AUD2', slide: 32 },
    { label: 'Innovation Builder AUD3', slide: 33 },
  ]},
  { title: '05 - Competitive', dividerSlide: 34, subs: [
    { label: 'Competitors Modular', slide: 35 },
    { label: 'Competitors RV', slide: 36 },
    { label: 'Competitor Forensics 5b', slide: 37 },
    { label: 'Brand Corporate Forensics 5c', slide: 38 },
    { label: 'ESOV Positioning', slide: 39 },
  ]},
  { title: '06 - Brand Strategy', dividerSlide: 40, subs: [
    { label: 'Strategy Pillars', slide: 41 },
    { label: 'Strategic Goal', slide: 42 },
    { label: 'KPI Tree', slide: 43 },
    { label: 'Initiatives', slide: 44 },
    { label: 'Roadmap Cadence', slide: 45 },
    { label: 'Kill Switches', slide: 46 },
    { label: 'Brand Opportunities', slide: 47 },
    { label: 'Five Actions', slide: 48 },
  ]},
  { title: '07 - Marketing', dividerSlide: 49, subs: [
    { label: 'AUD1 Channel Messaging', slide: 50 },
    { label: 'AUD1 Budget Measurement', slide: 51 },
    { label: 'AUD1 Tactics', slide: 52 },
    { label: 'AUD2 Channel Messaging', slide: 53 },
    { label: 'AUD2 Budget Measurement', slide: 54 },
    { label: 'AUD2 Tactics', slide: 55 },
    { label: 'AUD3 Channel Messaging', slide: 56 },
    { label: 'AUD3 Budget Measurement', slide: 57 },
    { label: 'AUD3 Tactics', slide: 58 },
  ]},
  { title: '08 - Social and Extended Analysis', dividerSlide: 59, subs: [
    { label: 'GEO Scorecard', slide: 60 },
    { label: 'News PR', slide: 61 },
    { label: 'Reviews Trust', slide: 62 },
    { label: 'Share Of Search', slide: 63 },
  ]},
  { title: '09 - Appendix', dividerSlide: 64, subs: [
    { label: 'CEPS Master', slide: 65 },
    { label: 'Data Gaps', slide: 66 },
    { label: 'Source Coverage', slide: 67 },
  ]},
  { title: '10 - Extended Market Intelligence', dividerSlide: 68, subs: [
    { label: 'Market Size ESOV', slide: 69 },
    { label: 'Industry Drivers', slide: 70 },
    { label: 'Macro Influences', slide: 71 },
    { label: 'Customer Problem', slide: 72 },
    { label: 'Value Proposition', slide: 73 },
  ]},
  { title: '11 - Methodology and Citations', dividerSlide: 74, subs: [
    { label: 'Methodology', slide: 75 },
    { label: 'Citations 1', slide: 76 },
    { label: 'Citations 2', slide: 77 },
    { label: 'Citations 3', slide: 78 },
    { label: 'Brand DNA', slide: 79 },
    { label: 'Strategy Pillars', slide: 80 },
    { label: 'Emerging Trends', slide: 81 },
    { label: 'Positioning Matrix', slide: 82 },
    { label: 'Data Sources', slide: 83 },
    { label: 'Back Cover', slide: 84 },
  ]},
];

// Cover + frame slides 1 + 2 are deck preamble (no TOC parent).
// Back cover slide 81 is deck closer.

